server:
  port: 8060

eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service # dan64 moi thu trong /employee den employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://employee-service # dan64 moi thu trong /employee den employee-service
          predicates:
            - Path=/department/**


management: 
  tracing:
    sampling:
      probability: 1.0